name: Run OSV Scanner 

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * 1"

jobs:
  scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.7.1"
    with:
      scan-args: |-
        --recursive
        --skip-git=true
        ./
